#cloud-config
runcmd:
  - echo "Starting enhanced local AI setup at $(date)" > /var/log/cloud-init-ai-setup.log
  - mkdir -p /root/setup
  - echo "Using locally uploaded setup scripts from D:\cloud-init-ai-setup\setup" >> /var/log/cloud-init-ai-setup.log
  - chmod +x /root/setup/*.sh
  - /root/setup/main.sh >> /var/log/cloud-init-ai-setup.log 2>&1 || echo "Setup failed, check /var/log/cloud-init-ai-setup.log for details"
