#cloud-config
write_files:
  - path: /var/log/setup.log
    content: |
      Cloud-Init Setup Log
      -------------------
    permissions: '0644'

runcmd:
  - echo "Starting setup process - $(date)" >> /var/log/setup.log
  - apt update -y
  - apt install -y bash
  - echo "Cloud-Init completed. Setup scripts will be executed via SSH. - $(date)" >> /var/log/setup.log
